project:
  type: website

website:
  title: "Correlation Between COIVD and Flu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scattered_graph.qmd
        text: Scattered Graph
      - href: sources.qmd
        text: Source
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



